#!/bin/sh
# Source run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

cp -r 0_init 0

for file in p T U
do
    cp 0/$file"_init" 0/$file
done

runApplication statInitLine

for file in p T U
do
    cp 0/$file"_st" 0/$file
done

runApplication eRhoReducedFoam
runApplication foamCalc magSqr U
runApplication sample

