#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -r 0 *e-0?
rm -r postProcessing
rm log.blockMesh  log.eRhoPimpleFoam  log.foamCalc  log.sample  log.statInitLine
